# publish and subscribe
costmap_topic: map
costmap_updates_topic: map_updates
visualize: true

# timing
planner_frequency: 5.0
progress_timeout: 30.0

# frontier construction
# min_frontier_size: 5.0
# min_frontier_size: 3.0
min_frontier_size: 1.0
# min_frontier_size: 0.5
# min_frontier_size: 2.5

# frontier cost weights
# alpha: 0.8
# alpha: 0.6
# alpha: 0.4
alpha: 0.2
proximity_factor: 5.0

# exploration strategy
# 0: closest centroid
# 1: closest cell + IG
# 2: closest cell
exploration_strategy: 1

# others
transform_tolerance: 0.3
